#!/bin/bash

# Directories
scriptName=$(basename "$0")

# Certificate Variables
VERBOSE=0
DURATION=365 # 1 year

safeExit() {
  trap - INT TERM EXIT
  exit
}

# Help Screen
help() {
  echo -n "${scriptName} [OPTIONS] -c=US --state=California

Generate self-signed root CA using OpenSSL

 Options:
  -c|--country         Country Name (2 letter code)
  -s|--state           State or Province Name (full name)
  -l|--locality        Locality Name (eg, city)
  -o|--organization    Organization Name (eg, company)
  -u|--unit            Organizational Unit Name (eg, section)
  -n|--common-name     Common Name (e.g. server FQDN or YOUR name)
  -e|--email           Email Address
  -p|--path            Path to output generated keys
  -d|--duration        Validity duration of the certificate (in days)
  -h|--help            Display this help and exit
  -v|--verbose         Verbose output
"
}

# Test output path is valid
testPath() {
  if [ ! -d $OUTPATH ]; then
    echo "The specified directory \"${OUTPATH}\" does not exist"
    exit 1
  fi
}

# Process Arguments
while [ "$1" != "" ]; do
  PARAM=$(echo "$1" | awk -F= '{print $1}')
  VALUE=$(echo "$1" | awk -F= '{print $2}')
  case $PARAM in
    -h|--help) help; safeExit ;;
    -c|--country) C=$VALUE ;;
    -s|--state) ST=$VALUE ;;
    -l|--locality) L=$VALUE ;;
    -o|--organization) O=$VALUE ;;
    -u|--unit) OU=$VALUE ;;
    -n|--common-name) CN=$VALUE ;;
    -e|--email) emailAddress=$VALUE ;;
    -p|--path) OUTPATH=$VALUE; testPath ;;
    -d|--duration) DURATION=$VALUE ;;
    -v|--verbose) VERBOSE=1 ;;
    *) echo "ERROR: unknown parameter \"$PARAM\""; help; exit 1 ;;
  esac
  shift
done

# Prompt for variables that were not provided in arguments
checkVariables() {
  # Country
  if [ -z "$C" ]; then
    echo -n "Country Name (2 letter code) [AU]: "
    read -r C
  fi

  # State
  if [ -z "$ST" ]; then
    echo -n "State or Province Name (full name) [Some-State]: "
    read -r ST
  fi

  # Locality
  if [ -z "$L" ]; then
    echo -n "Locality Name (eg, city) []: "
    read -r L
  fi

  # Organization
  if [ -z "$O" ]; then
    echo -n "Organization Name (eg, company) [Internet Widgits Pty Ltd]: "
    read -r O
  fi

  # Organizational Unit
  if [ -z "$OU" ]; then
    echo -n "Organizational Unit Name (eg, section) []: "
    read -r OU
  fi

  # Common Name
  if [ -z "$CN" ]; then
    echo -n "Common Name (e.g. server FQDN or YOUR name) []: "
    read -r CN
  fi

  # Email Address
  if [ -z "$emailAddress" ]; then
    echo -n "Email Address []: "
    read -r emailAddress
  fi
}

# Show variable values
showVals() {
  echo "Country: ${C}";
  echo "State: ${ST}";
  echo "Locality: ${L}";
  echo "Organization: ${O}";
  echo "Organization Unit: ${OU}";
  echo "Common Name: ${CN}";
  echo "Email: ${emailAddress}";
  echo "Output Path: ${OUTPATH}";
  echo "Certificate Duration (Days): ${DURATION}";
  echo "Verbose: ${VERBOSE}";
}

# Build root CA certificate
build() {
  # Santizie domain name for file name
  FILENAME=${CN/\*\./}

  # Set OUTPATH if not yet
  if [ -v $OUTPATH ]; then
    OUTPATH="./out/root/${FILENAME}/"
    mkdir -p ${OUTPATH}
  fi

  # Generate CA key & crt
  openssl genrsa -out "${OUTPATH}${FILENAME}_CA.key" 2048
  openssl req -x509 -new -nodes -key "${OUTPATH}${FILENAME}_CA.key" -sha256 -days "${DURATION}" -out "${OUTPATH}${FILENAME}_CA.pem" -subj "/C=${C}/ST=${ST}/L=${L}/O=${O}/OU=${OU}/CN=${CN}/emailAddress=${emailAddress}"
}

checkVariables
build
showVals
safeExit
