#!/bin/bash

# Directories
THIS=`readlink -f "${BASH_SOURCE[0]}" 2>/dev/null||echo $0`
DIR=`dirname "${THIS}"`
scriptName=$(basename "${THIS}")

# Certificate Variables
VERBOSE=0
DURATION=365 # 1 year

# Help Screen
help() {
  echo -n "${scriptName} [OPTIONS] -c=US --state=California

Generate self-signed root CA using OpenSSL

 Options:
  -c|--country         Country Name (2 letter code)
  -s|--state           State or Province Name (full name)
  -l|--locality        Locality Name (eg, city)
  -o|--organization    Organization Name (eg, company)
  -u|--unit            Organizational Unit Name (eg, section)
  -n|--common-name     Common Name (e.g. server FQDN or YOUR name)
  -e|--email           Email Address
  -p|--path            Path to output generated keys
  -d|--duration        Validity duration of the certificate (in days)
  -h|--help            Display this help and exit
  -v|--verbose         Verbose output
"
}

# Build root CA certificate
build() {
  # Santizie domain name for file name
  FILENAME=${CN/\*\./}

  # Set OUTPATH if not yet
  if [ -v $OUTPATH ]; then
    OUTPATH="$DIR/out/root/${FILENAME}/"
    mkdir -p ${OUTPATH}
  fi

  # Generate CA key & crt
  openssl genrsa -out "${OUTPATH}${FILENAME}_CA.key" 2048
  openssl req -x509 -new -nodes -key "${OUTPATH}${FILENAME}_CA.key" -sha256 -days "${DURATION}" -out "${OUTPATH}${FILENAME}_CA.pem" -subj "/C=${C}/ST=${ST}/L=${L}/O=${O}/OU=${OU}/CN=${CN}/emailAddress=${emailAddress}"
}

source "$DIR/common.sh"
checkVariables
build
showVals
safeExit
